ADD_SCENE(rollcall, start, Start)
ADD_SCENE(rollcall, capture, Capture)
ADD_SCENE(rollcall, auto, Auto)
ADD_SCENE(rollcall, diff, Diff)
ADD_SCENE(rollcall, craft, Craft)
ADD_SCENE(rollcall, about, About)
